version: '3'
services:
  database:
    volumes:
      - 'teamcity-mysql-data:/var/lib/mysql'
    environment:
      - 'MYSQL_ROOT_PASSWORD=mysqlsecret'
      - 'MYSQL_DATABASE=teamcity'
      - 'MYSQL_USER=teamcity'
      - 'MYSQL_PASSWORD=teamcity'
    image: mysql

  server:
    volumes:
      - 'teamcity-data:/data/teamcity_server/datadir'
      - 'teamcity-logs:/opt/teamcity/logs'
      - '/var/run/docker.sock:/var/run/docker.sock'
    links:
      - 'database:mysql'
      - 'bitbucket:bitbucket'
    ports:
      - '8111:8111'
    build:
      context: .
      dockerfile: Dockerfile.teamcity-server

  agent:
    volumes:
      - 'teamcity-agent-conf:/data/teamcity_agent/conf'
      - '/var/run/docker.sock:/var/run/docker.sock'
    links:
      - 'server:teamcity-server'
      - 'bitbucket:bitbucket'
    environment:
      - SERVER_URL=teamcity-server:8111
    image: jetbrains/teamcity-agent

  bitbucket:
    volumes:
      - 'bitbucket-data:/var/atlassian/application-data/bitbucket'
    ports:
      - '7990:7990'
      - '7999:7999'
    image: atlassian/bitbucket-server

volumes:
  teamcity-data:
  teamcity-logs:
  teamcity-agent-conf:
  teamcity-mysql-data:
  bitbucket-data:
